---
name: Release

on:
  push:
    branches: [main]

jobs:
  ci:
    # name: Lint & Test
    uses: ./.github/workflows/ci.yaml

  release:
    name: Release
    needs: [ci]
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      packages: write
      pull-requests: write
    steps:
      - uses: open-turo/actions-python/release@v1
        id: release
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
